name: Main Branch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test - Unit and Integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven Install
        run: mvn -f commons/pom.xml -B clean install
      - name: Maven Package
        run: mvn -f commons/pom.xml -B clean package
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Install
        run: mvn -B clean install
      - name: Maven Verify
        run: mvn -B clean verify